### ISSUE TITLE
Can't see command text as typing

### ISSUE THREAD

**Issue by troyhart** [guileen/terminal-status#62]
The process of entering a command into the terminal is completely blind. As I type I can not see anything. When I press enter, if I haven't typed anything incorrect everything works, but it's frustrating to not be able to see what command I'm entering.

**Comment by shazron** [comment]
I can verify this bug. This package is essentially unusable because of this. Using atom 0.188.0 and terminal-status 1.6.0

**Comment by jrabary** [comment]
+1

**Comment by IonRod** [comment]
I've got the same problem(

**Comment by mkremers** [comment]
Same problem (Atom 0.189.0 on Ubuntu 14.10).
