### ISSUE TITLE
Execute user's .bashrc or .profile or custom terminal startup script?

### ISSUE THREAD

**Issue by twss** [guileen/terminal-status#7]
As a specific example, the terminal window is unable to access the path as a normal terminal session on OS X would. This means I don't have any access to rvm/nvm etc., which makes it quite useless, as I have to revert to a traditional terminal.

Is it possible to specify a a startup script anywhere?

**Comment by danielbayley** [comment]
@guileen Terminal on OS X opens as an interactive **login** shell (thus sourcing ~/.bashrc). Could this package not just mimic this behavior? 

Something like `[/usr/bin/env] bash -ilc`… maybe?

At the moment if I do `echo $0` it returns `/bin/sh` which is the least useful.
