### ISSUE TITLE
Tasks still running

### ISSUE THREAD

**Issue by visualcookie** [guileen/terminal-status#73]
Hi,

killed all console tasks but he's still executing them. Could be a bug.

**Comment by visualcookie** [comment]
Is this issue still present? I really want to use this package but I can't.

**Comment by pandres95** [comment]
Unfortunately is still present, is something related to the event listening. I'm on it

**Comment by pandres95** [comment]
Please install `terminal-status@1.6.8`

**Comment by visualcookie** [comment]
Installed... still getting the following:
```
Uncaught TypeError: Cannot read property 'offsetTop' of undefined
```
