### ISSUE TITLE
Launch Terminal From Project Folder

### ISSUE THREAD

**Issue by daverogers** [guileen/terminal-status#76]
Apologies if I'm mistaken on how to do this without expending your development time (still relatively new to Atom/Terminal Status) but I noticed every terminal window opens in my profile folder (on Mac). If there isn't a way to automatically launch terminal from the base/currently selected project folder, that would be an excellent option to build in.

**Comment by pandres95** [comment]
Actually, Terminal Status launches recognizing the actual project folder, but under some circumstances it may be not working. Check you've got the latest update and you're into a working file of the desired project. Otherwise, it defaults for user's profile folder.

**Comment by daverogers** [comment]
Thank you! I thought I read that in the code, so yeah, must be on my end. I'll take another look at it later and see what might be snagging it up.
