### ISSUE TITLE
Holding Shift+Enter decreasing editor height

### ISSUE THREAD

**Issue by luizrocha13** [guileen/terminal-status#84]
The editor is decreasing when keep pressed shift+enter on linux 64 bits.

**Comment by luizrocha13** [comment]
The problem was solved by placing the following code in styles.less file.

atom-panel.bottom {
  border-top: 0px solid #000000;
}

**Comment by pandres95** [comment]
Thanks for telling us about the issue, would you like to make a PR with the solution?
